POST https://penaval.com/api/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "Penaval123"
}

### products
GET https://penaval.com/api/products?limit=1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsImlhdCI6MTY5NTA3NjIyMCwiZXhwIjoxNjk1NTA4MjIwfQ.lpDNvhNEaxRqRzGoyOkhjj8GrIIN7Vg26G1pCmi_0bU

### brands
GET https://penaval.com/api/brands?limit=1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsImlhdCI6MTY5NTA3NjIyMCwiZXhwIjoxNjk1NTA4MjIwfQ.lpDNvhNEaxRqRzGoyOkhjj8GrIIN7Vg26G1pCmi_0bU

### places
GET https://penaval.com/api/places?limit=1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsImlhdCI6MTY5NTA3NjIyMCwiZXhwIjoxNjk1NTA4MjIwfQ.lpDNvhNEaxRqRzGoyOkhjj8GrIIN7Vg26G1pCmi_0bU

### Providers
GET https://penaval.com/api/providers?limit=1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsImlhdCI6MTY5NTA3NjIyMCwiZXhwIjoxNjk1NTA4MjIwfQ.lpDNvhNEaxRqRzGoyOkhjj8GrIIN7Vg26G1pCmi_0bU