# Generated by Django 4.2.5 on 2023-09-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='proveedor',
            new_name='provider',
        ),
    ]
