# Generated by Django 4.2.5 on 2023-09-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_rename_proveedor_shopping_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingdetail',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_detail', to='shopping.shopping'),
        ),
    ]
