# Generated by Django 4.2 on 2024-02-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proform',
            name='client',
        ),
    ]
