# Generated by Django 4.2 on 2024-03-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_proform_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proform',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforms', to='sales.client'),
        ),
    ]
