# Generated by Django 4.2 on 2024-12-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_proform_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URl de la factura'),
        ),
    ]
