# Generated by Django 4.2.5 on 2023-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_stok_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pucharse_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio Compra'),
        ),
    ]
